name: legal_start_up
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  dotted_border: ^2.0.0+2
  flutter_screenutil: ^5.5.3+2
  flutter_rating_stars: ^1.0.3+4
  smooth_star_rating_null_safety: ^1.0.4+2
  avatar_stack: ^1.1.2
  image_stack: ^2.1.1


  expansion_tile_card: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
        - asset: assets/fonts/PoppinsLight.ttf
        - asset: assets/fonts/PoppinsSemiBold.ttf
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGroteskBold.ttf
          weight: 700
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikRomanMedium.ttf
          weight: 500

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
